config/routes.rb
Rails.application.routes.draw do

  get    'contact_form/new'
  get    'contact_form/create'
  get    'password_resets/new'
  get    'password_resets/edit'
  get    'sessions/new'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :contact_forms

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home_logged_out.html.erb
<div class="center jumbotron">
  <h1>Welcome to Grunt<sup>α</sup>!</h1>

  <div class="grog">
    <%= image_tag("icon.png", alt: "Grog") %>
  </div>

  <h2>
    Yet another Microposting Platform, but instead of 140 characters, you get 14.<br><br>
    It's a Micro-Microposting Platform. A Micro<sup>2</sup>posting Platform.<br><br>
    GET CREATIVE.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary btn-signup" %>
</div>

  <div id="note">
    NOTE: As Grunt is an early alpha all data is subject to possible deletion. Sorry.
  </div>

<div class="center">
  <p class="powered-text">Powered by</p>
  <div class="powered">
  <%= link_to image_tag("rails.png", alt: "Rails logo"),
                                   'http://rubyonrails.org/', target: :_blank %>
  <%= link_to image_tag("bootstrap.png", alt: "Bootstrap logo"),
                                   'https://getbootstrap.com/', target: :_blank %>
  <%= link_to image_tag("sass.png", alt: "Sass logo"),
                                   'http://sass-lang.com/', target: :_blank %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Grunt</h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2 content-box">
    <p>
    Grunt started as a simple dummy application to gain experience using Ruby on Rails and has since evolved into my ideal form of social media: that which does not allow much commentary.<br /><br />


    <strong>Upcoming Features</strong><br />
    <s>-Account Authentication/Activation</s><br />
    <s>-User Profile</s><br />
    <s>-Gravatar capabilities</s><br />
    <s>-Microposts</s><br />
    <s>-User relationships</s><br />
    <s>-Layout animations</s><br />
    <s>-Mobile styles</s><br />
    <s>-Custom input for Grunts with limit restrictions and character counter</s><br />
    -Asynchronous follow/unfollow of other users without refreshing the page<br />
    -Asynchronous posting without refreshing the page<br />
    -User screennames<br />
    -Custom url for users based on screenname<br />
    -User searching<br />
    -Individual micropost pages<br />
    -Photo upload and storage using AWS<br />
    -Custom uploaded avatars using AWS<br />
    -A like system (using ♧ instead of ♡, clubs/caveman)<br />
    -A page to store liked posts ("Clubhouse")<br />
    -User comments on Grunts<br />
    -User tagging on Grunts<br />
    -Tags for Grunts<br />
    -Notification system<br />
    -Encrypted direct messaging<br />
    -Emoji picker for desktop<br />
    -Expand 14 characters to 28 characters <br />
    -Mobile app using Flutter/Dart and Rails API<br /><br />
    

    Stay tuned for more exciting features!<br />
    -Geoff
    </p>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2 content-box">
    <p>
      
    </p>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2 content-box helpbox">
    <button class="accordion">Signing Up</button>
      <div class="panel">
        <p>
          From the <%= link_to "Home Page", root_path %> click the button that says <%= link_to "Sign up now!", signup_path %>
        </p>
        <%= image_tag("help/homepage.png", alt: "Home Page", title: "Home Page", class: "help-img-desktop") %>
        <%= image_tag("help/homepage-mobile.jpg", alt: "Home Page", title: "Home Page", class: "help-img-mobile") %>
        <p>
          Fill in your information and click "Create my Account".
        </p>
        <%= image_tag("help/signup.png", alt: "Sign Up", title: "Sign Up", class: "help-img-desktop") %>
        <%= image_tag("help/signup-mobile.jpg", alt: "Sign Up", title: "Sign Up", class: "help-img-mobile") %>
        <p>
          Check your email for an activation link. Click on the link to be logged in for the first time! Welcome to Grunt.
        </p>
      </div>

    <button class="accordion">Logging In</button>
      <div class="panel">
        <p class="help-p-desktop">
          Click the button in the top menu that says <%= link_to "Log In", login_path %>.
        </p>
        <p class="help-p-mobile">
          Tap the button in the top menu that says <%= link_to "Log In", login_path %>.
        </p>
        <p class="help-p-desktop">
          Fill in your email address and password and click "Log In".
        </p>
        <p class="help-p-mobile">
          Fill in your email address and password and tap "Log In".
        </p>
        <%= image_tag("help/login.png", alt: "Log In", title: "Log In", class: "help-img-desktop") %>
        <%= image_tag("help/login-mobile.jpg", alt: "Log In", title: "Log In", alt: "", title: "", class: "help-img-mobile") %>
        <p>
          Upon successful login you will be taken to your <%= link_to "Feed", root_path %>. Happy Grunting!
        </p>
      </div>

    <button class="accordion">Viewing Your Profile</button>
      <div class="panel">
        <p class="help-p-desktop">
          While logged in, click "Account" in the top menu and click "<%= link_to "Profile", current_user %>".
        </p>
        <p class="help-p-mobile">
          While logged in, click the <%= link_to '<i class="material-icons md-36">account_circle</i>'.html_safe, current_user %> icon in the top menu.
        </p>
        <%= image_tag("", alt: "", title: "", class: "help-img-desktop") %>
        <%= image_tag("", alt: "", title: "", class: "help-img-mobile") %>
      </div>

    <button class="accordion">Editing Your Profile</button>
      <div class="panel">
        <p class="help-p-desktop">
          While logged in, click "Account" in the top menu and click "Edit Profile".
        </p>
        <p class="help-p-mobile">
          While logged in, click the <i class="material-icons md-36">settings</i> icon in the top menu and click "Edit Profile".
        </p>
        <%= image_tag("", alt: "", title: "", class: "help-img-desktop") %>
        <%= image_tag("", alt: "", title: "", class: "help-img-mobile") %>
      </div>

    <button class="accordion">Posting a Grunt</button>
      <div class="panel">
      <p class="help-p-desktop">
        Go to your <%= link_to "Feed", root_path %> or <%= link_to "Profile", current_user %> and locate the input box labeled "Compose Grunt".
      </p>
      <p class="help-p-mobile">
        Go to your <%= link_to image_tag("icon.png", alt: "Feed"), root_path%><%= link_to "Feed", root_path %> or <%= link_to '<i class="material-icons md-36">account_circle</i>'.html_safe, current_user %><%= link_to "Profile", current_user %> and locate the input box labeled "Compose Grunt".
      </p>
      <%= image_tag("", alt: "", title: "", class: "help-img-desktop") %>
      <%= image_tag("", alt: "", title: "", class: "help-img-mobile") %>

      <p class="help-p-desktop">
        Click the input box and start typing your Grunt. Note how many characters you have left before you hit the maximum limit.
      </p>
      <p class="help-p-mobile">
        Tap the input box and start typing your Grunt. Note how many characters you have left before you hit the maximum limit.
      </p>
      <%= image_tag("", alt: "", title: "", class: "help-img-desktop") %>
      <%= image_tag("", alt: "", title: "", class: "help-img-mobile") %>
      </div>

    <button class="accordion">Deleting a Grunt</button>
      <div class="panel">
        <p class="help-p-desktop">
          If you're not happy with how your Grunt turned out, that's ok. Anywhere your Grunt is visible you can just click "Delete" after the timestamp to be rid of it.
        </p>
        <p class="help-p-mobile">
          If you're not happy with how your Grunt turned out, that's ok. Anywhere your Grunt is visible you can just tap "Delete" after the timestamp to be rid of it.
        </p>
        <%= image_tag("", alt: "", title: "", class: "help-img-desktop") %>
        <%= image_tag("", alt: "", title: "", class: "help-img-mobile") %>
      </div>

    <button class="accordion">Viewing All Users</button>
      <div class="panel">
        <p>
        <p class="help-p-desktop">
          While logged in, click "<%= link_to "Users", users_path %>" in the top menu.
        </p>
        <p class="help-p-mobile">
          While logged in, click the <%= link_to '<i class="material-icons md-36">people</i>'.html_safe, users_path %> icon in the top menu.
        </p>
        <%= image_tag("", alt: "", title: "", class: "help-img-desktop") %>
        <%= image_tag("", alt: "", title: "", class: "help-img-mobile") %>
        </p>
      </div>

    <button class="accordion">Following a Grunter</button>
      <div class="panel">
        <p class="help-p-desktop">
          Anywhere a Grunter you do not follow is visible, click the "Follow" button next to their name or Grunt.
        </p>
        <p class="help-p-mobile">
          Anywhere a Grunter you do not follow is visible, tap the "Follow" button next to their name or Grunt.
        </p>
        <%= image_tag("", alt: "", title: "", class: "help-img-desktop") %>
        <%= image_tag("", alt: "", title: "", class: "help-img-mobile") %>
        <%= image_tag("", alt: "", title: "", class: "help-img-desktop") %>
        <%= image_tag("", alt: "", title: "", class: "help-img-mobile") %>
      </div>

    <button class="accordion">Unfollowing a Grunter</button>
      <div class="panel">
        <p>
        <p class="help-p-desktop">
          Anywhere a Grunter you follow is visible, click the "Unfollow" button next to their name or Grunt.
        </p>
        <p class="help-p-mobile">
          Anywhere a Grunter you follow is visible, tap the "Unfollow" button next to their name or Grunt.
        </p>
        <%= image_tag("", alt: "", title: "", class: "help-img-desktop") %>
        <%= image_tag("", alt: "", title: "", class: "help-img-mobile") %>
        <%= image_tag("", alt: "", title: "", class: "help-img-desktop") %>
        <%= image_tag("", alt: "", title: "", class: "help-img-mobile") %>
        </p>
      </div>

  </div>
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
    acc[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var panel = this.nextElementSibling;
        if (panel.style.display === "block") {
            panel.style.display = "none";
        } else {
            panel.style.display = "block";
        }
    });
}
</script>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<div class="row mobile-row">
  <aside class="content-box profile-box">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="content-box feed-box">
  <%= render 'layouts/flash' %>
    <h3>Grunt Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>
<% else %>
  <%= render 'home_logged_out' %>
<% end %>