config/routes.rb
Rails.application.routes.draw do

  get    'contact_form/new'
  get    'contact_form/create'
  get    'password_resets/new'
  get    'password_resets/edit'
  get    'sessions/new'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :contact_forms

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger signup-flash">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>

  <div class="homepage-pagination">
    <%= will_paginate(@feed_items,
                      renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer,
                      class: 'text-center') %>
  </div>
<% else %>
  <p class="havent-grunted">You have not Grunted yet! Get started with the form on the left.</p>
  <p class="havent-grunted">And while you're at it, why not follow some other <%= link_to "users", users_url %> to see their Grunts on the homepage too!</p>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :content, id: "gruntinput", maxlength: "14", placeholder: "Compose Grunt", autocomplete: "off" %>
  </div>
  <p id="gruntcounter">14 characters left</p>
  <%= f.submit "Grunt", class: "btn btn-primary btn-grunt" %>
  <span class="picture" style="display:none;">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript"> 
var $input =   $('#gruntinput')
var $counter = $('#gruntcounter')
var updateCounterText = function() {
  var max = 14;
  if ($input.val().length < max - 1) {
    $counter.html((max - $(this).val().length) + " characters left");
  } else if ($input.val().length == max - 1 ) {  
    $counter.html("1 character left");
  } else {
    $input.val($input.val().substr(0, max));
    $counter.html("<p style='color:maroon;'>0 characters left</span>");
  }
}
$input.bind("change keyup input", updateCounterText);
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <div class="stats_wrapper">
    <a href="<%= following_user_path(@user) %>">
      <strong id="following" class="stat">
        <%= @user.following.count %>
      </strong>
      following
    </a>
    <a href="<%= followers_user_path(@user) %>">
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
      followers
    </a>
  </div>
</div>

app/views/shared/_user_info.html.erb
<div class="gravatar_wrapper">
<%= link_to gravatar_tag(current_user.email), current_user %>
</div>
<h1><%= link_to current_user.name, current_user %></h1>

<div class="profile_link_view"><%= pluralize(current_user.microposts.count, "Grunt") %></div>