config/routes.rb
Rails.application.routes.draw do

  get    'contact_form/new'
  get    'contact_form/create'
  get    'password_resets/new'
  get    'password_resets/edit'
  get    'sessions/new'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :contact_forms

end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Grunt", root_path %> created by <%= link_to "Geoff Ramler", "http://geofframler.com", :target => "_blank" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help",   help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= mail_to "geoff@ramler.net", "Contact", cc: "geoffrey.ramler@gmail.com", subject: "Grunt" %></li>
      <li class="mobile-hidden"><%= link_to "Ruby on Rails", 'http://rubyonrails.org/',
                                        target: :_blank %></li>
      <li class="mobile-hidden"><%= link_to "Bootstrap", 'https://getbootstrap.com/',
                                        target: :_blank %>
      <li class="mobile-hidden"><%= link_to "Sass", 'http://sass-lang.com/',
                                        target: :_blank %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header id="navbar" class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("logo.png", alt: "Grunt logo", id: "logoimage"), root_path, id: "logo" %>
    <%= link_to "Grunt", root_path, id: "logotext" %>
    <sup><div id="alpha-menu">α</div></sup>
    <nav class="menu-desktop">
      <ul class="nav navbar-nav navbar-right">
        
        <% if logged_in? %>
          <li><%= link_to "Home",  root_path%></li>
          <li><%= link_to "Users", users_path %></li>
          <li id="dropdown" class="dropdown">
            <a href="#" id="dropdown-toggle" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log Out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
            <li><%= link_to "Help", help_path %></li>
          <li><%= link_to '<button class="btn btn-nav-login">Log In</button>'.html_safe, login_path %></li>
        <% end %>
      </ul>
    </nav>

    <nav class="menu-mobile">
      <ul class="nav navbar-nav navbar-right">
        
        <% if logged_in? %>
          <li><%= link_to '<i class="material-icons md-36">account_circle</i>'.html_safe, current_user %></li>
          <li><%= link_to '<i class="material-icons md-36">people</i>'.html_safe, users_path %></li>
          <li id="dropdown" class="dropdown">
            <a href="#" id="dropdown-toggle" class="dropdown-toggle" data-toggle="dropdown">
              <i class="material-icons md-36">settings</i>
            </a>
            <ul class="dropdown-menu">
              
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "Help", help_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log Out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '<i class="material-icons md-36">help</i>'.html_safe, help_path %></li>
          <li><%= link_to '<button class="btn btn-nav-login">Log In</button>'.html_safe, login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'fata-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 90]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>